export const nowPlayingMovies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/backdrop_101.jpg",
      genre_ids: [28, 80, 53],
      id: 101001,
      original_language: "en",
      original_title: "Edge of Midnight",
      overview:
        "A former detective races against time through a neon-lit city to stop a conspiracy that could change the world.",
      popularity: 522.731,
      poster_path: "/poster_101.jpg",
      release_date: "2026-05-15",
      title: "Edge of Midnight",
      video: false,
      vote_average: 7.8,
      vote_count: 4621,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_102.jpg",
      genre_ids: [14, 12, 10751],
      id: 101002,
      original_language: "en",
      original_title: "Starlight Academy",
      overview:
        "An aspiring young magician enrolls in a whimsical academy where friendship and courage unlock real magic.",
      popularity: 318.194,
      poster_path: "/poster_102.jpg",
      release_date: "2026-04-30",
      title: "Starlight Academy",
      video: false,
      vote_average: 7.1,
      vote_count: 1894,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_103.jpg",
      genre_ids: [18, 10752],
      id: 101003,
      original_language: "fr",
      original_title: "La Dernière Lettre",
      overview:
        "Set in post-war Europe, a woman discovers a letter that unravels her family's hidden past and reshapes her future.",
      popularity: 142.009,
      poster_path: "/poster_103.jpg",
      release_date: "2026-05-10",
      title: "The Last Letter",
      video: false,
      vote_average: 8.0,
      vote_count: 784,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_104.jpg",
      genre_ids: [27, 53],
      id: 101004,
      original_language: "en",
      original_title: "Hollow Night",
      overview:
        "A small town is terrorized when shadows take the shape of the town's secrets; a group of teens must survive until dawn.",
      popularity: 256.442,
      poster_path: "/poster_104.jpg",
      release_date: "2026-05-22",
      title: "Hollow Night",
      video: false,
      vote_average: 6.5,
      vote_count: 1213,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_105.jpg",
      genre_ids: [18, 10749],
      id: 101005,
      original_language: "hi",
      original_title: "Dil aur Dhun",
      overview:
        "A heartfelt dramedy about two strangers whose chance meeting on a train leads to an unexpected journey of self-discovery.",
      popularity: 198.055,
      poster_path: "/poster_105.jpg",
      release_date: "2026-05-08",
      title: "Dil aur Dhun",
      video: false,
      vote_average: 7.4,
      vote_count: 2040,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_106.jpg",
      genre_ids: [878, 12],
      id: 101006,
      original_language: "en",
      original_title: "Aurora Drift",
      overview:
        "A crew aboard a deep-space vessel chase a rogue signal that could be the key to humanity's next evolution.",
      popularity: 412.88,
      poster_path: "/poster_106.jpg",
      release_date: "2026-05-01",
      title: "Aurora Drift",
      video: false,
      vote_average: 7.6,
      vote_count: 3310,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_107.jpg",
      genre_ids: [99],
      id: 101007,
      original_language: "en",
      original_title: "Voices of the River",
      overview:
        "Documentary following communities along a threatened river, exploring culture, industry, and resilience.",
      popularity: 58.21,
      poster_path: "/poster_107.jpg",
      release_date: "2026-04-20",
      title: "Voices of the River",
      video: false,
      vote_average: 7.9,
      vote_count: 412,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_108.jpg",
      genre_ids: [18],
      id: 101008,
      original_language: "en",
      original_title: "Letters to Tomorrow",
      overview:
        "An elderly writer reflects on lost love by composing letters to the people who shaped her life.",
      popularity: 134.67,
      poster_path: "/poster_108.jpg",
      release_date: "2026-05-12",
      title: "Letters to Tomorrow",
      video: false,
      vote_average: 7.3,
      vote_count: 660,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_109.jpg",
      genre_ids: [80, 18],
      id: 101009,
      original_language: "en",
      original_title: "City of Ashes",
      overview:
        "An investigative journalist uncovers corruption linking a corporate behemoth to a wave of suspicious arsons.",
      popularity: 211.95,
      poster_path: "/poster_109.jpg",
      release_date: "2026-05-05",
      title: "City of Ashes",
      video: false,
      vote_average: 7.0,
      vote_count: 1502,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_110.jpg",
      genre_ids: [16, 10751],
      id: 101010,
      original_language: "en",
      original_title: "Moonflower",
      overview:
        "An animated fable about a child who tends a magical garden that blooms under moonlight.",
      popularity: 176.3,
      poster_path: "/poster_110.jpg",
      release_date: "2026-04-25",
      title: "Moonflower",
      video: false,
      vote_average: 8.2,
      vote_count: 2890,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_111.jpg",
      genre_ids: [80, 18],
      id: 101011,
      original_language: "en",
      original_title: "Rogue Protocol",
      overview:
        "A retired hacker pulls one last job to expose a data cartel, but the plan goes sideways when loyalties shift.",
      popularity: 299.12,
      poster_path: "/poster_111.jpg",
      release_date: "2026-05-20",
      title: "Rogue Protocol",
      video: false,
      vote_average: 6.9,
      vote_count: 980,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_112.jpg",
      genre_ids: [35, 18],
      id: 101012,
      original_language: "en",
      original_title: "Weekend Woes",
      overview:
        "Two mismatched roommates try to salvage a disastrous weekend that turns into a series of comedic misadventures.",
      popularity: 148.01,
      poster_path: "/poster_112.jpg",
      release_date: "2026-05-02",
      title: "Weekend Woes",
      video: false,
      vote_average: 6.8,
      vote_count: 540,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_113.jpg",
      genre_ids: [18, 10752],
      id: 101013,
      original_language: "es",
      original_title: "Caminos Cruzados",
      overview:
        "Cross-cultural stories interweave in a port city where migrants pursue hope against bureaucratic odds.",
      popularity: 85.44,
      poster_path: "/poster_113.jpg",
      release_date: "2026-04-28",
      title: "Crossed Paths",
      video: false,
      vote_average: 7.5,
      vote_count: 322,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_114.jpg",
      genre_ids: [18, 10752],
      id: 101014,
      original_language: "en",
      original_title: "The Hollow Door",
      overview:
        "Homeowners find a hidden door that releases fears into the world; they must confront their pasts to close it.",
      popularity: 225.6,
      poster_path: "/poster_114.jpg",
      release_date: "2026-05-18",
      title: "The Hollow Door",
      video: false,
      vote_average: 6.4,
      vote_count: 1107,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_115.jpg",
      genre_ids: [18, 10752],
      id: 101015,
      original_language: "en",
      original_title: "Second Chance Summer",
      overview:
        "Old friends reunite in a lakeside town where an unexpected illness forces them to reconcile and forgive.",
      popularity: 162.77,
      poster_path: "/poster_115.jpg",
      release_date: "2026-05-03",
      title: "Second Chance Summer",
      video: false,
      vote_average: 7.2,
      vote_count: 870,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_116.jpg",
      genre_ids: [14, 12, 10751],
      id: 101016,
      original_language: "en",
      original_title: "The Gilded Compass",
      overview:
        "A young cartographer discovers an enchanted compass that reveals hidden worlds and dangerous rivals.",
      popularity: 244.5,
      poster_path: "/poster_116.jpg",
      release_date: "2026-05-21",
      title: "The Gilded Compass",
      video: false,
      vote_average: 7.7,
      vote_count: 2201,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_117.jpg",
      genre_ids: [878, 18],
      id: 101017,
      original_language: "en",
      original_title: "Through the Static",
      overview:
        "After a mysterious broadcast manipulates memory, a small team races to decode the signal before it's too late.",
      popularity: 197.33,
      poster_path: "/poster_117.jpg",
      release_date: "2026-05-07",
      title: "Through the Static",
      video: false,
      vote_average: 7.0,
      vote_count: 1299,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_118.jpg",
      genre_ids: [35, 18],
      id: 101018,
      original_language: "en",
      original_title: "Grandma's Garage Sale",
      overview:
        "A community bands together to save a grandmother's home by turning an ordinary garage sale into a laugh-filled fundraiser.",
      popularity: 119.9,
      poster_path: "/poster_118.jpg",
      release_date: "2026-04-22",
      title: "Grandma's Garage Sale",
      video: false,
      vote_average: 6.9,
      vote_count: 430,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_119.jpg",
      genre_ids: [18, 10752],
      id: 101019,
      original_language: "en",
      original_title: "Borrowed Time",
      overview:
        "A struggling small-town lawyer takes on a wrongful conviction case that exposes long-buried community secrets.",
      popularity: 153.44,
      poster_path: "/poster_119.jpg",
      release_date: "2026-05-11",
      title: "Borrowed Time",
      video: false,
      vote_average: 7.1,
      vote_count: 689,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_120.jpg",
      genre_ids: [16, 10751],
      id: 101020,
      original_language: "en",
      original_title: "Puppet Parade",
      overview:
        "A lively puppet troupe helps a shy child find her voice and heal after a family loss.",
      popularity: 138.02,
      poster_path: "/poster_120.jpg",
      release_date: "2026-04-29",
      title: "Puppet Parade",
      video: false,
      vote_average: 7.6,
      vote_count: 1015,
    },
  ],
  dates: {
    maximum: "2026-05-31",
    minimum: "2026-04-20",
  },
  total_pages: 5,
  total_results: 100,
};

export const videoBackground = [
  {
    id: 101001,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "EDGE_OF_MIDNIGHT_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-20T15:00:00.000Z",
        id: "vid_101001_1",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Teaser",
        key: "EDGE_OF_MIDNIGHT_TSR",
        site: "YouTube",
        size: 720,
        type: "Teaser",
        official: true,
        published_at: "2026-04-05T12:00:00.000Z",
        id: "vid_101001_2",
      },
    ],
  },
  {
    id: 101002,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "STARLIGHT_ACADEMY_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-10T14:30:00.000Z",
        id: "vid_101002_1",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Clip - First Day",
        key: "STARLIGHT_ACADEMY_CLIP1",
        site: "YouTube",
        size: 720,
        type: "Clip",
        official: false,
        published_at: "2026-04-25T18:00:00.000Z",
        id: "vid_101002_2",
      },
    ],
  },
  {
    id: 101003,
    results: [
      {
        iso_639_1: "fr",
        iso_3166_1: "FR",
        name: "Bande-annonce officielle",
        key: "DERNIERE_LETTRE_BA",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-08T10:00:00.000Z",
        id: "vid_101003_1",
      },
    ],
  },
  {
    id: 101004,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "HOLLOW_NIGHT_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-18T20:00:00.000Z",
        id: "vid_101004_1",
      },
    ],
  },
  {
    id: 101005,
    results: [
      {
        iso_639_1: "hi",
        iso_3166_1: "IN",
        name: "Official Trailer",
        key: "DIL_AUR_DHUN_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-15T09:30:00.000Z",
        id: "vid_101005_1",
      },
    ],
  },
  {
    id: 101006,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "AURORA_DRIFT_TRL1",
        site: "YouTube",
        size: 2160,
        type: "Trailer",
        official: true,
        published_at: "2026-03-30T16:00:00.000Z",
        id: "vid_101006_1",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Behind the Scenes",
        key: "AURORA_DRIFT_BTS1",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: false,
        published_at: "2026-04-10T11:00:00.000Z",
        id: "vid_101006_2",
      },
    ],
  },
  {
    id: 101007,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "VOICES_OF_THE_RIVER_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-01T13:00:00.000Z",
        id: "vid_101007_1",
      },
    ],
  },
  {
    id: 101008,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "LETTERS_TO_TOMORROW_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-12T18:30:00.000Z",
        id: "vid_101008_1",
      },
    ],
  },
  {
    id: 101009,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "CITY_OF_ASHES_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-07T19:00:00.000Z",
        id: "vid_101009_1",
      },
    ],
  },
  {
    id: 101010,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "MOONFLOWER_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-05T08:00:00.000Z",
        id: "vid_101010_1",
      },
    ],
  },
  {
    id: 101011,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "ROGUE_PROTOCOL_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-22T21:00:00.000Z",
        id: "vid_101011_1",
      },
    ],
  },
  {
    id: 101012,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "WEEKEND_WOES_TRL1",
        site: "YouTube",
        size: 720,
        type: "Trailer",
        official: true,
        published_at: "2026-04-15T14:00:00.000Z",
        id: "vid_101012_1",
      },
    ],
  },
  {
    id: 101013,
    results: [
      {
        iso_639_1: "es",
        iso_3166_1: "ES",
        name: "Tráiler oficial",
        key: "CAMINOS_CRUZADOS_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-03T11:00:00.000Z",
        id: "vid_101013_1",
      },
    ],
  },
  {
    id: 101014,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "HOLLOW_DOOR_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-19T20:30:00.000Z",
        id: "vid_101014_1",
      },
    ],
  },
  {
    id: 101015,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "SECOND_CHANCE_SUMMER_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-09T17:00:00.000Z",
        id: "vid_101015_1",
      },
    ],
  },
  {
    id: 101016,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "GILDED_COMPASS_TRL1",
        site: "YouTube",
        size: 2160,
        type: "Trailer",
        official: true,
        published_at: "2026-04-25T16:30:00.000Z",
        id: "vid_101016_1",
      },
    ],
  },
  {
    id: 101017,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "THROUGH_THE_STATIC_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-14T18:45:00.000Z",
        id: "vid_101017_1",
      },
    ],
  },
  {
    id: 101018,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "GRANDMAS_GARAGE_SALE_TRL1",
        site: "YouTube",
        size: 720,
        type: "Trailer",
        official: true,
        published_at: "2026-04-06T09:15:00.000Z",
        id: "vid_101018_1",
      },
    ],
  },
  {
    id: 101019,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "BORROWED_TIME_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-11T15:20:00.000Z",
        id: "vid_101019_1",
      },
    ],
  },
  {
    id: 101020,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "PUPPET_PARADE_TRL1",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2026-04-13T10:40:00.000Z",
        id: "vid_101020_1",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Teaser",
        key: "PUPPET_PARADE_TSR1",
        site: "Vimeo",
        size: 720,
        type: "Teaser",
        official: false,
        published_at: "2026-03-28T12:10:00.000Z",
        id: "vid_101020_2",
      },
    ],
  },
];
