export const nowPlayingMovies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/backdrop_101.jpg",
      genre_ids: [28, 80, 53],
      id: 101001,
      original_language: "en",
      original_title: "Edge of Midnight",
      overview:
        "A former detective races against time through a neon-lit city to stop a conspiracy that could change the world.",
      popularity: 522.731,
      poster_path: "/poster_101.jpg",
      release_date: "2026-05-15",
      title: "Edge of Midnight",
      video: false,
      vote_average: 7.8,
      vote_count: 4621,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_102.jpg",
      genre_ids: [14, 12, 10751],
      id: 101002,
      original_language: "en",
      original_title: "Starlight Academy",
      overview:
        "An aspiring young magician enrolls in a whimsical academy where friendship and courage unlock real magic.",
      popularity: 318.194,
      poster_path: "/poster_102.jpg",
      release_date: "2026-04-30",
      title: "Starlight Academy",
      video: false,
      vote_average: 7.1,
      vote_count: 1894,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_103.jpg",
      genre_ids: [18, 10752],
      id: 101003,
      original_language: "fr",
      original_title: "La Dernière Lettre",
      overview:
        "Set in post-war Europe, a woman discovers a letter that unravels her family's hidden past and reshapes her future.",
      popularity: 142.009,
      poster_path: "/poster_103.jpg",
      release_date: "2026-05-10",
      title: "The Last Letter",
      video: false,
      vote_average: 8.0,
      vote_count: 784,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_104.jpg",
      genre_ids: [27, 53],
      id: 101004,
      original_language: "en",
      original_title: "Hollow Night",
      overview:
        "A small town is terrorized when shadows take the shape of the town's secrets; a group of teens must survive until dawn.",
      popularity: 256.442,
      poster_path: "/poster_104.jpg",
      release_date: "2026-05-22",
      title: "Hollow Night",
      video: false,
      vote_average: 6.5,
      vote_count: 1213,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_105.jpg",
      genre_ids: [18, 10749],
      id: 101005,
      original_language: "hi",
      original_title: "Dil aur Dhun",
      overview:
        "A heartfelt dramedy about two strangers whose chance meeting on a train leads to an unexpected journey of self-discovery.",
      popularity: 198.055,
      poster_path: "/poster_105.jpg",
      release_date: "2026-05-08",
      title: "Dil aur Dhun",
      video: false,
      vote_average: 7.4,
      vote_count: 2040,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_106.jpg",
      genre_ids: [878, 12],
      id: 101006,
      original_language: "en",
      original_title: "Aurora Drift",
      overview:
        "A crew aboard a deep-space vessel chase a rogue signal that could be the key to humanity's next evolution.",
      popularity: 412.88,
      poster_path: "/poster_106.jpg",
      release_date: "2026-05-01",
      title: "Aurora Drift",
      video: false,
      vote_average: 7.6,
      vote_count: 3310,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_107.jpg",
      genre_ids: [99],
      id: 101007,
      original_language: "en",
      original_title: "Voices of the River",
      overview:
        "Documentary following communities along a threatened river, exploring culture, industry, and resilience.",
      popularity: 58.21,
      poster_path: "/poster_107.jpg",
      release_date: "2026-04-20",
      title: "Voices of the River",
      video: false,
      vote_average: 7.9,
      vote_count: 412,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_108.jpg",
      genre_ids: [18],
      id: 101008,
      original_language: "en",
      original_title: "Letters to Tomorrow",
      overview:
        "An elderly writer reflects on lost love by composing letters to the people who shaped her life.",
      popularity: 134.67,
      poster_path: "/poster_108.jpg",
      release_date: "2026-05-12",
      title: "Letters to Tomorrow",
      video: false,
      vote_average: 7.3,
      vote_count: 660,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_109.jpg",
      genre_ids: [80, 18],
      id: 101009,
      original_language: "en",
      original_title: "City of Ashes",
      overview:
        "An investigative journalist uncovers corruption linking a corporate behemoth to a wave of suspicious arsons.",
      popularity: 211.95,
      poster_path: "/poster_109.jpg",
      release_date: "2026-05-05",
      title: "City of Ashes",
      video: false,
      vote_average: 7.0,
      vote_count: 1502,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_110.jpg",
      genre_ids: [16, 10751],
      id: 101010,
      original_language: "en",
      original_title: "Moonflower",
      overview:
        "An animated fable about a child who tends a magical garden that blooms under moonlight.",
      popularity: 176.3,
      poster_path: "/poster_110.jpg",
      release_date: "2026-04-25",
      title: "Moonflower",
      video: false,
      vote_average: 8.2,
      vote_count: 2890,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_111.jpg",
      genre_ids: [80, 18],
      id: 101011,
      original_language: "en",
      original_title: "Rogue Protocol",
      overview:
        "A retired hacker pulls one last job to expose a data cartel, but the plan goes sideways when loyalties shift.",
      popularity: 299.12,
      poster_path: "/poster_111.jpg",
      release_date: "2026-05-20",
      title: "Rogue Protocol",
      video: false,
      vote_average: 6.9,
      vote_count: 980,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_112.jpg",
      genre_ids: [35, 18],
      id: 101012,
      original_language: "en",
      original_title: "Weekend Woes",
      overview:
        "Two mismatched roommates try to salvage a disastrous weekend that turns into a series of comedic misadventures.",
      popularity: 148.01,
      poster_path: "/poster_112.jpg",
      release_date: "2026-05-02",
      title: "Weekend Woes",
      video: false,
      vote_average: 6.8,
      vote_count: 540,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_113.jpg",
      genre_ids: [18, 10752],
      id: 101013,
      original_language: "es",
      original_title: "Caminos Cruzados",
      overview:
        "Cross-cultural stories interweave in a port city where migrants pursue hope against bureaucratic odds.",
      popularity: 85.44,
      poster_path: "/poster_113.jpg",
      release_date: "2026-04-28",
      title: "Crossed Paths",
      video: false,
      vote_average: 7.5,
      vote_count: 322,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_114.jpg",
      genre_ids: [18, 10752],
      id: 101014,
      original_language: "en",
      original_title: "The Hollow Door",
      overview:
        "Homeowners find a hidden door that releases fears into the world; they must confront their pasts to close it.",
      popularity: 225.6,
      poster_path: "/poster_114.jpg",
      release_date: "2026-05-18",
      title: "The Hollow Door",
      video: false,
      vote_average: 6.4,
      vote_count: 1107,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_115.jpg",
      genre_ids: [18, 10752],
      id: 101015,
      original_language: "en",
      original_title: "Second Chance Summer",
      overview:
        "Old friends reunite in a lakeside town where an unexpected illness forces them to reconcile and forgive.",
      popularity: 162.77,
      poster_path: "/poster_115.jpg",
      release_date: "2026-05-03",
      title: "Second Chance Summer",
      video: false,
      vote_average: 7.2,
      vote_count: 870,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_116.jpg",
      genre_ids: [14, 12, 10751],
      id: 101016,
      original_language: "en",
      original_title: "The Gilded Compass",
      overview:
        "A young cartographer discovers an enchanted compass that reveals hidden worlds and dangerous rivals.",
      popularity: 244.5,
      poster_path: "/poster_116.jpg",
      release_date: "2026-05-21",
      title: "The Gilded Compass",
      video: false,
      vote_average: 7.7,
      vote_count: 2201,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_117.jpg",
      genre_ids: [878, 18],
      id: 101017,
      original_language: "en",
      original_title: "Through the Static",
      overview:
        "After a mysterious broadcast manipulates memory, a small team races to decode the signal before it's too late.",
      popularity: 197.33,
      poster_path: "/poster_117.jpg",
      release_date: "2026-05-07",
      title: "Through the Static",
      video: false,
      vote_average: 7.0,
      vote_count: 1299,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_118.jpg",
      genre_ids: [35, 18],
      id: 101018,
      original_language: "en",
      original_title: "Grandma's Garage Sale",
      overview:
        "A community bands together to save a grandmother's home by turning an ordinary garage sale into a laugh-filled fundraiser.",
      popularity: 119.9,
      poster_path: "/poster_118.jpg",
      release_date: "2026-04-22",
      title: "Grandma's Garage Sale",
      video: false,
      vote_average: 6.9,
      vote_count: 430,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_119.jpg",
      genre_ids: [18, 10752],
      id: 101019,
      original_language: "en",
      original_title: "Borrowed Time",
      overview:
        "A struggling small-town lawyer takes on a wrongful conviction case that exposes long-buried community secrets.",
      popularity: 153.44,
      poster_path: "/poster_119.jpg",
      release_date: "2026-05-11",
      title: "Borrowed Time",
      video: false,
      vote_average: 7.1,
      vote_count: 689,
    },
    {
      adult: false,
      backdrop_path: "/backdrop_120.jpg",
      genre_ids: [16, 10751],
      id: 101020,
      original_language: "en",
      original_title: "Puppet Parade",
      overview:
        "A lively puppet troupe helps a shy child find her voice and heal after a family loss.",
      popularity: 138.02,
      poster_path: "/poster_120.jpg",
      release_date: "2026-04-29",
      title: "Puppet Parade",
      video: false,
      vote_average: 7.6,
      vote_count: 1015,
    },
  ],
  dates: {
    maximum: "2026-05-31",
    minimum: "2026-04-20",
  },
  total_pages: 5,
  total_results: 100,
};
